version: "3.9"

services:
  api:
    build: .
    container_name: desafio-fit-api
    environment:
      DATABASE_URL: sqlite:////app/local.db
      JWT_SECRET_KEY: change-me
      JWT_ALGORITHM: HS256
      JWT_ACCESS_TOKEN_EXPIRES_MIN: "60"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir app

volumes:
  sqlite_data:
